#!/usr/bin/bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias d="cd -"
alias dirs="dirs -v"
alias dus="du -s *"
alias duss="du -s * | sort -n"
alias eg="env | grep -i"
alias f="fg"
alias h="history | tail -n $LINES"
alias hg="history | grep -i"
alias j="jobs -l"
alias psu='ps -fu $USER'
alias shlvl="echo $SHLVL"
alias uniqcount="sort | uniq -c | sort -n"
alias uniqs="sort | uniq"
alias wcl="wc -l"

if [[ $EMACS ]]; then
    alias emacs="emacsclient -n"
else
    alias emacs="emacs -nw"
fi
alias emc="emacs"
alias emcc="emacsclient -n"

# ls alias
alias ls="ls -F -T 0 -N --color=auto"

alias l="ls"
alias ll="ls -l"
alias la="ls -a"
alias lla="ls -la"
alias lh="ls -lh"
alias lt="ls -ltr"
alias lsd="ls -d"

# find alias
alias fd="find -L . -name"
alias fdf="find -L . -type f -name"
alias fdd="find -L . -type d -name"
alias findd="find -L . -type d"
alias findf="find -L . -type f"
alias findc="find -L . \( -name '*.c' -o -name '*.cpp' \)"
alias findh="find -L . \( -name '*.h' -o -name '*.hpp' \)"
alias findch="find -L . \( -name '*.c' -o -name '*.cpp' -o -name '*.h' -o -name '*.hpp' \)"
alias findmake="find -L . -name '[Mm]ake*'"

# grep alias
alias grepi="grep -i"
alias xgrep='GREP_OPTIONS="--color=always" xargs -0 grep -0'
alias grepc="findc -print0 | xgrep -nH"
alias greph="findh -print0 | xgrep -nH"
alias grepch="findch -print0 | xgrep -nH"
alias grepmake="findmake -print0 | xgrep -nH"

# Date converter functions
date2unix()
{
    TZ=UTC date +%s -d"$*"
}

date2human()
{
    TZ=UTC date -d @$@
}
