#!/bin/bash

DOTFILES_DIR="$(pwd)"
DOTFILES_HOME_DIR="${DOTFILES_DIR}/home"

for file in "${DOTFILES_HOME_DIR}"/.*; do
    # realpath is used create a link relative to the $HOME directory *without* expanding symlinks; I
    # need this when the $DOTFILES_DIR itself is a symlink to another directory.
    ln -fsv -- "$(realpath -ms --relative-to $HOME -- ${file})" $HOME/
done

unset file
unset DOTFILES_DIR
unset DOTFILES_HOME_DIR
