#!/bin/bash

DOTFILES_DIR="$(pwd)"

declare -a DOTFILES=(
    bin
    "${DOTFILES_DIR}/home/".*
)

for file in "${DOTFILES[@]}"; do
    if ! [ -a "${file}" ]; then
        echo Warning: file \""${file}"\" does not exist.
    else
        # realpath is used create a link relative to the $HOME directory *without* expanding
        # symlinks; I need this when the $DOTFILES_DIR itself is a symlink to another directory.
        ln -fsv -- "$(realpath -ms --relative-to $HOME -- ${file})" $HOME/
    fi
done

unset file
unset DOTFILES_DIR
unset DOTFILES
