#!/bin/bash

DOTFILES_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)

# DEBUG
# echo dotfile_dir:$DOTFILES_DIR

declare -a DOTFILES=(
    $DOTFILES_DIR/bin
    $(find $DOTFILES_DIR/home -type f)
)

for file in "${DOTFILES[@]}"; do
    if ! [ -a "${file}" ]; then
        echo Warning: file \""${file}"\" does not exist.
    else
        # realpath is used create a link relative to the $HOME directory *without* expanding
        # symlinks; I need this when the $DOTFILES_DIR itself is a symlink to another directory.
        ln -fsv -- "$(realpath -mqs --relative-to $HOME -- ${file})" $HOME/
    fi
done

unset file
unset DOTFILES
unset DOTFILES_DIR
